### ISSUE TITLE
Please help addrinfo not found.

### ISSUE THREAD

**Issue by Lieonkp** [viveris/jtag-boundary-scanner#1]
g:\jtag-boundary-scanner\jtag_boundary_scanner_gui\win32\socket.c(124) : error C2079: 'hints' uses undefined struct 'addrinfo'

**Comment by jfdelnero** [comment]
Which visual studio version are you using ?

**Comment by jfdelnero** [comment]
With the old VC 6.0 compiler you need the platform SDK for VC6.
