### ISSUE TITLE
BSDL parsing bug

### ISSUE THREAD

**Issue by Oremuss** [viveris/jtag-boundary-scanner#12]
Hello, I have encountered soma small "bug" and I think it will be some sort of part of parsing BSDL file.

 I am using TMS320F28035 processor and everything is working fine in GUI except input reading in GPIO24. In GUI the input mark "I" is always checked (always showing 1) whether it is set to input or output (OE and O disabled). But its only visual reading of pin ( actual value when in output mode is switching between 0 - 3.3V a.k.a. 0 to 1. At first I thought that it is something with HW and then I checked it with Devkit instead of PCB and same problem occurred again. 
When I excluded HW I checked BSDL file and GPIO24 is last element of constant PIN_MAP_STRING as well as attribute BOUNDARY_REGISTER. Now it looked very suspicious being last element and not working properly at same time. So I did small change and swapped GPIO21 and GPIO24 (so GPIO21 would be last element in PIN_MAP_STRING and BOUNDARY_REGISTER) and GPIO24 started to read input correctly and GPIO21 became broken (again only reading  is showing always checked mark in "I").  

So IMHO there is something wrong with indexing or parsing last element of  PIN_MAP_STRING or BOUNDARY_REGISTER or something related. 

[TMS320F2803X_TQFP.txt](https://github.com/viveris/jtag-boundary-scanner/files/10939768/TMS320F2803X_TQFP.txt)

**Comment by Oremuss** [comment]
Cool, let me know if you find anything or if you want to describe it more properly, test something or debug it :)

**Comment by jfdelnero** [comment]
@Oremuss I didn't managed to reproduce the issue, but if possible please retry with the latest version, i have fixed several issues.

**Comment by jfdelnero** [comment]
i finally got this issue on one of our project ... : this wasn't a parser issue, but a bug in the FTDI probe layer... This is now fixed in the latest version. (v2.6.6.1 at this date).
