### ISSUE TITLE
BSDL file crashes 

### ISSUE THREAD

**Issue by galacticstudios** [viveris/jtag-boundary-scanner#15]
If I open the attached BSDL file in JTAG Boundary Scanner, the program crashes.
[1508AS_J84.zip](https://github.com/viveris/jtag-boundary-scanner/files/13342733/1508AS_J84.zip)

**Comment by galacticstudios** [comment]
This is on Windows 10, using Version 2.52.

**Comment by jfdelnero** [comment]
Thanks. This is fixed. A new release is planned, probably this week.

**Comment by jfdelnero** [comment]
v2.6.3.1 released.
[v2.6.3.1](https://github.com/viveris/jtag-boundary-scanner/releases/tag/v2.6.3.1)
