### ISSUE TITLE
Unable to parse external symbol setOutputFunc  

### ISSUE THREAD

**Issue by GrayLoach** [viveris/jtag-boundary-scanner#5]
I use Visual Studio 2017 and have changed the v142 to v141, but this problem always occurs.  Does this mean that I have to install Visual Studio 2019 ?  But my PC has too much Visual Studio version and I'm so tired of this.

**Comment by honigal** [comment]
Just change the the function name 'setOutputFunc' to 'setOutputFunc_script' in libjtagcore.def file.
you should be golden.

Alex

**Comment by jfdelnero** [comment]
Exact. i will fix the .def file.

**Comment by jfdelnero** [comment]
Fixed.

**Comment by GrayLoach** [comment]
> Just change the the function name 'setOutputFunc' to 'setOutputFunc_script' in libjtagcore.def file. you should be golden.
> 
> Alex

Wow, you can really dance !
